server:
  port: 8080
springdoc:
  swagger-ui:
    path: '/user/swagger'
    disable-swagger-default-url: true
    operations-sorter: 'alpha'
    tags-sorter: 'alpha'

spring:
  profiles:
    active: 'prod'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 최대 10개 (default 설정과 같은 값)
      maximum-pool-size: 10
      # 최소 idle connection 2개
      # (default 설정은 10개이므로 많이 줄인 것임)
      minimum-idle: 2
      # 300,000ms = 5분 (default 설정은 10분임)
      idle-timeout: 300000
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  access-token-expiration-ms: 21600000    # 6시간
