spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 3600000
logging:
  level:
    root: WARN
domain:
  mail:
    url: ${EMAIL_URL}