server:
  port: 8001
jwt:
  secret: secret-64-byte-minimum-secret-key-which-must-be-long-enough-for-hmac
  access-token-expiration-ms: 3600000
springdoc:
  swagger-ui:
    path: '/swagger'
    disable-swagger-default-url: true
    operations-sorter: 'alpha'
    tags-sorter: 'alpha'

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydatabase
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379