server:
  port: 8080
springdoc:
  swagger-ui:
    path: '/user/swagger'
    disable-swagger-default-url: true
    operations-sorter: 'alpha'
    tags-sorter: 'alpha'

spring:
  profiles:
    active: 'local'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  access-token-expiration-ms: 21600000    # 6시간
